#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TinyDancerXamarin.Tests.Resource", IsApplication=true)]

namespace TinyDancerXamarin.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TinyDancerXamarin.Resource.Dimension.metric_band_width = global::TinyDancerXamarin.Tests.Resource.Dimension.metric_band_width;
			global::TinyDancerXamarin.Resource.Drawable.fpsmeterring_bad = global::TinyDancerXamarin.Tests.Resource.Drawable.fpsmeterring_bad;
			global::TinyDancerXamarin.Resource.Drawable.fpsmeterring_good = global::TinyDancerXamarin.Tests.Resource.Drawable.fpsmeterring_good;
			global::TinyDancerXamarin.Resource.Drawable.fpsmeterring_medium = global::TinyDancerXamarin.Tests.Resource.Drawable.fpsmeterring_medium;
			global::TinyDancerXamarin.Resource.Layout.meter_view = global::TinyDancerXamarin.Tests.Resource.Layout.meter_view;
			global::TinyDancerXamarin.Resource.String.library_name = global::TinyDancerXamarin.Tests.Resource.String.library_name;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::TinyDancerXamarin.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::TinyDancerXamarin.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::TinyDancerXamarin.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::TinyDancerXamarin.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::TinyDancerXamarin.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::TinyDancerXamarin.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::TinyDancerXamarin.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::TinyDancerXamarin.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::TinyDancerXamarin.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::TinyDancerXamarin.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::TinyDancerXamarin.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::TinyDancerXamarin.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::TinyDancerXamarin.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::TinyDancerXamarin.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::TinyDancerXamarin.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::TinyDancerXamarin.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::TinyDancerXamarin.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::TinyDancerXamarin.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::TinyDancerXamarin.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::TinyDancerXamarin.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::TinyDancerXamarin.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::TinyDancerXamarin.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int metric_band_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fpsmeterring_bad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fpsmeterring_good = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fpsmeterring_medium = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int OptionHostName = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int OptionPort = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int OptionRemoteServer = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int OptionsButton = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int ResultFullName = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int ResultMessage = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int ResultResultState = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int ResultRunSingleMethodTest = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int ResultStackTrace = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int ResultsFailed = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int ResultsId = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int ResultsIgnored = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int ResultsInconclusive = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int ResultsMessage = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int ResultsPassed = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ResultsResult = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int RunTestsButton = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int TestSuiteListView = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int meter_view = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int options = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int results = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int test_result = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int test_suite = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
